/* Q.15) Write a program to print the look and say series 
The Look-and-Say sequence is generated by describing the
previous term rather than doing normal arithmetic.

Start with:

1

Now "look" at it and "say" what you see:

1 → one 1 → 11

Then:

11 → two 1s → 21

Then:

21 → one 2, one 1 → 1211

Then:

1211 → one 1, one 2, two 1s → 111221

So the sequence is:

1
11
21
1211
111221
312211
13112221
...

The important rule
You count consecutive identical digits and describe them.

For example: 111221, Read it as: three 1s, two 2s, one 1

Therefore the next term is: 312211 */

/* This solution uses integer values, but there is an easier 
solution using strings */

#include <stdio.h>

void LookAndSay(int n)
{
    int term = 1;
    int count, digit, temp;

    for(int i = 1; i <= n; i++)
    {
        printf("%d ", term);

        temp = term;
        int next = 0;
        int place = 1;

        while(temp != 0)
        {
            digit = temp % 10;
            count = 0;

            while(temp != 0 && temp % 10 == digit)
            {
                count++;
                temp = temp / 10;
            }

            next = (count * 10 + digit) * place + next;
            place = place * 100;
        }

        term = next;
    }
}

int main()
{
    int n;

    printf("Enter the number of terms: ");
    scanf("%d", &n);

    printf("Look-and-Say Series: ");
    LookAndSay(n);

    return 0;
}